# Generated by Django 4.2 on 2023-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_name_products_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
