# Generated by Django 3.2.18 on 2023-05-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
